### PR TITLE
Migrate plugin and demo project to NativeScript 3.0

### PR DESCRIPTION
**Pull request by radeva**

### CODE REVIEW

**Comment by hypery2k** [comment]
thanks for your PR. Will have a look at it during the next days. But from first look seems good.

**Comment by radeva** [comment]
We found some issues for ios which we're trying to solve and send an update soon.

**Comment by hypery2k** [comment]
Ok, feel free to update the PR.

**Comment by hypery2k** [comment]
Thanks for your PR

**Pull request merged**
